# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/p22user/p22ectrl/tools/lm4_monitor/mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LM4_Monitor(object):
    def setupUi(self, LM4_Monitor):
        LM4_Monitor.setObjectName(_fromUtf8("LM4_Monitor"))
        LM4_Monitor.resize(1278, 356)
        self.centralwidget = QtGui.QWidget(LM4_Monitor)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setPointSize(62)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lbStatus = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.lbStatus.setFont(font)
        self.lbStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lbStatus.setObjectName(_fromUtf8("lbStatus"))
        self.horizontalLayout.addWidget(self.lbStatus)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lbPetraC_3 = QtGui.QLabel(self.centralwidget)
        self.lbPetraC_3.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.lbPetraC_3.setFont(font)
        self.lbPetraC_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbPetraC_3.setObjectName(_fromUtf8("lbPetraC_3"))
        self.horizontalLayout_4.addWidget(self.lbPetraC_3)
        self.lbPetraC_4 = QtGui.QLabel(self.centralwidget)
        self.lbPetraC_4.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.lbPetraC_4.setFont(font)
        self.lbPetraC_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbPetraC_4.setObjectName(_fromUtf8("lbPetraC_4"))
        self.horizontalLayout_4.addWidget(self.lbPetraC_4)
        self.lbPcurrent = QtGui.QLabel(self.centralwidget)
        self.lbPcurrent.setMinimumSize(QtCore.QSize(75, 0))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.lbPcurrent.setFont(font)
        self.lbPcurrent.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbPcurrent.setObjectName(_fromUtf8("lbPcurrent"))
        self.horizontalLayout_4.addWidget(self.lbPcurrent)
        self.lbPetraA_3 = QtGui.QLabel(self.centralwidget)
        self.lbPetraA_3.setMinimumSize(QtCore.QSize(75, 0))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.lbPetraA_3.setFont(font)
        self.lbPetraA_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbPetraA_3.setObjectName(_fromUtf8("lbPetraA_3"))
        self.horizontalLayout_4.addWidget(self.lbPetraA_3)
        self.lbPetraC = QtGui.QLabel(self.centralwidget)
        self.lbPetraC.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.lbPetraC.setFont(font)
        self.lbPetraC.setAlignment(QtCore.Qt.AlignCenter)
        self.lbPetraC.setObjectName(_fromUtf8("lbPetraC"))
        self.horizontalLayout_4.addWidget(self.lbPetraC)
        self.lbPbunches = QtGui.QLabel(self.centralwidget)
        self.lbPbunches.setMinimumSize(QtCore.QSize(75, 0))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.lbPbunches.setFont(font)
        self.lbPbunches.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbPbunches.setObjectName(_fromUtf8("lbPbunches"))
        self.horizontalLayout_4.addWidget(self.lbPbunches)
        self.lbPetraA = QtGui.QLabel(self.centralwidget)
        self.lbPetraA.setMinimumSize(QtCore.QSize(30, 0))
        self.lbPetraA.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.lbPetraA.setFont(font)
        self.lbPetraA.setText(_fromUtf8(""))
        self.lbPetraA.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbPetraA.setObjectName(_fromUtf8("lbPetraA"))
        self.horizontalLayout_4.addWidget(self.lbPetraA)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lbPS2C = QtGui.QLabel(self.centralwidget)
        self.lbPS2C.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.lbPS2C.setFont(font)
        self.lbPS2C.setAlignment(QtCore.Qt.AlignCenter)
        self.lbPS2C.setObjectName(_fromUtf8("lbPS2C"))
        self.horizontalLayout_2.addWidget(self.lbPS2C)
        self.lbPS2 = QtGui.QLabel(self.centralwidget)
        self.lbPS2.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.lbPS2.setFont(font)
        self.lbPS2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbPS2.setObjectName(_fromUtf8("lbPS2"))
        self.horizontalLayout_2.addWidget(self.lbPS2)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lbLM4 = QtGui.QLabel(self.centralwidget)
        self.lbLM4.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.lbLM4.setFont(font)
        self.lbLM4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbLM4.setObjectName(_fromUtf8("lbLM4"))
        self.horizontalLayout_2.addWidget(self.lbLM4)
        self.lbV2C = QtGui.QLabel(self.centralwidget)
        self.lbV2C.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.lbV2C.setFont(font)
        self.lbV2C.setAlignment(QtCore.Qt.AlignCenter)
        self.lbV2C.setObjectName(_fromUtf8("lbV2C"))
        self.horizontalLayout_2.addWidget(self.lbV2C)
        self.lbV2 = QtGui.QLabel(self.centralwidget)
        self.lbV2.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.lbV2.setFont(font)
        self.lbV2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbV2.setObjectName(_fromUtf8("lbV2"))
        self.horizontalLayout_2.addWidget(self.lbV2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        LM4_Monitor.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(LM4_Monitor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1278, 30))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        LM4_Monitor.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(LM4_Monitor)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        LM4_Monitor.setStatusBar(self.statusbar)

        self.retranslateUi(LM4_Monitor)
        QtCore.QMetaObject.connectSlotsByName(LM4_Monitor)

    def retranslateUi(self, LM4_Monitor):
        LM4_Monitor.setWindowTitle(_translate("LM4_Monitor", "MainRoutine", None))
        self.label.setText(_translate("LM4_Monitor", "Beam:", None))
        self.lbStatus.setText(_translate("LM4_Monitor", "OFF!!!", None))
        self.lbPetraC_3.setText(_translate("LM4_Monitor", "PETRA:", None))
        self.lbPetraC_4.setText(_translate("LM4_Monitor", "current:", None))
        self.lbPcurrent.setText(_translate("LM4_Monitor", "80", None))
        self.lbPetraA_3.setText(_translate("LM4_Monitor", "mA", None))
        self.lbPetraC.setText(_translate("LM4_Monitor", "bunches:", None))
        self.lbPbunches.setText(_translate("LM4_Monitor", "80", None))
        self.lbPS2C.setText(_translate("LM4_Monitor", "PS2:", None))
        self.lbPS2.setText(_translate("LM4_Monitor", "closed", None))
        self.label_2.setText(_translate("LM4_Monitor", "LM4:", None))
        self.lbLM4.setText(_translate("LM4_Monitor", "no beam", None))
        self.lbV2C.setText(_translate("LM4_Monitor", "V2:", None))
        self.lbV2.setText(_translate("LM4_Monitor", "closed", None))

