# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/condition_setup.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConditionSetup(object):
    def setupUi(self, ConditionSetup):
        ConditionSetup.setObjectName("ConditionSetup")
        ConditionSetup.resize(455, 155)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConditionSetup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.cmb_attribute = QtWidgets.QComboBox(ConditionSetup)
        self.cmb_attribute.setObjectName("cmb_attribute")
        self.gridLayout.addWidget(self.cmb_attribute, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(ConditionSetup)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(ConditionSetup)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.le_device = QtWidgets.QLineEdit(ConditionSetup)
        self.le_device.setObjectName("le_device")
        self.gridLayout.addWidget(self.le_device, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(ConditionSetup)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.le_name = QtWidgets.QLineEdit(ConditionSetup)
        self.le_name.setObjectName("le_name")
        self.gridLayout.addWidget(self.le_name, 0, 1, 1, 1)
        self.cmd_delete_me = QtWidgets.QPushButton(ConditionSetup)
        self.cmd_delete_me.setObjectName("cmd_delete_me")
        self.gridLayout.addWidget(self.cmd_delete_me, 0, 3, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(ConditionSetup)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.cmb_condition = QtWidgets.QComboBox(ConditionSetup)
        self.cmb_condition.setObjectName("cmb_condition")
        self.cmb_condition.addItem("")
        self.cmb_condition.addItem("")
        self.cmb_condition.addItem("")
        self.horizontalLayout_7.addWidget(self.cmb_condition)
        self.label_12 = QtWidgets.QLabel(ConditionSetup)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.dsp_threshold = QtWidgets.QDoubleSpinBox(ConditionSetup)
        self.dsp_threshold.setDecimals(6)
        self.dsp_threshold.setMinimum(-1000000000.0)
        self.dsp_threshold.setMaximum(1000000000.0)
        self.dsp_threshold.setObjectName("dsp_threshold")
        self.horizontalLayout_7.addWidget(self.dsp_threshold)
        self.sp_threshold = QtWidgets.QSpinBox(ConditionSetup)
        self.sp_threshold.setMinimum(-1000000000)
        self.sp_threshold.setMaximum(1000000000)
        self.sp_threshold.setObjectName("sp_threshold")
        self.horizontalLayout_7.addWidget(self.sp_threshold)
        self.le_value = QtWidgets.QLineEdit(ConditionSetup)
        self.le_value.setObjectName("le_value")
        self.horizontalLayout_7.addWidget(self.le_value)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem2 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(ConditionSetup)
        QtCore.QMetaObject.connectSlotsByName(ConditionSetup)

    def retranslateUi(self, ConditionSetup):
        _translate = QtCore.QCoreApplication.translate
        ConditionSetup.setWindowTitle(_translate("ConditionSetup", "Dialog"))
        self.label_8.setText(_translate("ConditionSetup", "Tango device"))
        self.label_9.setText(_translate("ConditionSetup", "Attribute"))
        self.label_10.setText(_translate("ConditionSetup", "Name"))
        self.le_name.setText(_translate("ConditionSetup", "New condition"))
        self.cmd_delete_me.setText(_translate("ConditionSetup", "Delete"))
        self.label_11.setText(_translate("ConditionSetup", "Should be"))
        self.cmb_condition.setItemText(0, _translate("ConditionSetup", "equal"))
        self.cmb_condition.setItemText(1, _translate("ConditionSetup", "more"))
        self.cmb_condition.setItemText(2, _translate("ConditionSetup", "less"))
        self.label_12.setText(_translate("ConditionSetup", "than"))
